name: ci

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile
      - .github/workflows/ci.yaml

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - 
        name: Check Hash
        run: echo "${{ env.git_hash }}"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arunkumar1418/platform-python-app:${{ env.git_hash }}
    outputs:
      commit_id: ${{ env.git_hash }}

  CD:
    runs-on: self-hosted
    needs: CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Modify values file
        shell: bash
        run: |
          echo "Updating image tag to: ${{needs.ci.outputs.commit_id}}"
          sed -i "s/tag:.*/tag: \"${{needs.ci.outputs.commit_id}}\"/" charts/platform-python/values.yaml
          cat charts/platform-python/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'
          token: ${{ secrets.PAT_TOKEN }}
      - name: Install argocd
        shell: bash
        run: |
          curl -sSL -o install.sh https://raw.githubusercontent.com/argoproj/argo-cd/stable/install.sh
          chmod +x install.sh
          sudo ./install.sh argocd
          which argocd
          argocd version --client
          argocd --help

      - name: argocd app sync
        shell: bash
        run:  |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

          
