name: ci

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile
      - .github/workflows/ci.yaml

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - 
        name: Check Hash
        run: echo "${{ env.hash }}"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arunkumar1418/platform-python-app:${{ env.hash }}